version: '2.0'
services:
  chatgpt-on-wechat:
    build:
      context: ./
      dockerfile: Dockerfile.alpine.latest
    image: zhayujie/chatgpt-on-wechat
    container_name: sample-chatgpt-on-wechat
    # host.docker.internal无效的情况下使用host方法走代理
    network_mode: host
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    environment:
      OPEN_AI_API_KEY: ''
      # OPEN_AI_PROXY: 'http://host.docker.internal:7890'
      OPEN_AI_PROXY: 'http://127.0.0.1:7890'
      SINGLE_CHAT_PREFIX: '["小真同学", "@小真同学"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[小真同学] "'
      GROUP_CHAT_PREFIX: '["@小真同学"]'
      GROUP_NAME_WHITE_LIST: '["ULTRA泰裤辣", "chat居pt"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: "False"
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600